const std = @import("std");

const __android = @import("__android.zig");
const __windows = @import("__windows.zig");
const __linux = @import("__linux.zig");
const window = @import("window.zig");
const __system = @import("__system.zig");
const system = @import("system.zig");
const math = @import("math.zig");

pub const general_input = @import("general_input.zig");
pub const xbox_pad_input = @import("xbox_pad_input.zig");
const xfit = @import("xfit.zig");

pub const key =
    if (xfit.platform == .windows)
    enum(u16) {
        A = 'A',
        B = 'B',
        C = 'C',
        D = 'D',
        E = 'E',
        F = 'F',
        G = 'G',
        H = 'H',
        I = 'I',
        J = 'J',
        K = 'K',
        L = 'L',
        M = 'M',
        N = 'N',
        O = 'O',
        P = 'P',
        Q = 'Q',
        R = 'R',
        S = 'S',
        T = 'T',
        U = 'U',
        V = 'V',
        W = 'W',
        X = 'X',
        Y = 'Y',
        Z = 'Z',
        One = '1',
        Two = '2',
        Three = '3',
        Four = '4',
        Five = '5',
        Six = '6',
        Seven = '7',
        Eight = '8',
        Nine = '9',
        Zero = '0',
        Numpad1 = __windows.win32.VK_NUMPAD1,
        Numpad2 = __windows.win32.VK_NUMPAD2,
        Numpad3 = __windows.win32.VK_NUMPAD3,
        Numpad4 = __windows.win32.VK_NUMPAD4,
        Numpad5 = __windows.win32.VK_NUMPAD5,
        Numpad6 = __windows.win32.VK_NUMPAD6,
        Numpad7 = __windows.win32.VK_NUMPAD7,
        Numpad8 = __windows.win32.VK_NUMPAD8,
        Numpad9 = __windows.win32.VK_NUMPAD9,
        Numpad0 = __windows.win32.VK_NUMPAD0,
        NumLock = __windows.win32.VK_NUMLOCK,
        ScrollLock = __windows.win32.VK_SCROLL,
        CapsLock = __windows.win32.VK_CAPITAL,
        NumpadAdd = __windows.win32.VK_ADD,
        NumpadSubtract = __windows.win32.VK_SUBTRACT,
        NumpadMultiply = __windows.win32.VK_MULTIPLY,
        NumpadDivide = __windows.win32.VK_DIVIDE,
        NumpadDot = __windows.win32.VK_DECIMAL,
        Enter = __windows.win32.VK_RETURN, // Numpad and Standard
        LShift = __windows.win32.VK_LSHIFT,
        RShift = __windows.win32.VK_RSHIFT,
        Shift = __windows.win32.VK_SHIFT,
        Ctrl = __windows.win32.VK_CONTROL,
        LCtrl = __windows.win32.VK_LCONTROL,
        RCtrl = __windows.win32.VK_RCONTROL,
        Tap = __windows.win32.VK_TAB,
        Esc = __windows.win32.VK_ESCAPE,
        IMEProcess = __windows.win32.VK_PROCESSKEY,
        Apps = __windows.win32.VK_APPS,
        SpaceBar = __windows.win32.VK_SPACE,
        F1 = __windows.win32.VK_F1,
        F2 = __windows.win32.VK_F2,
        F3 = __windows.win32.VK_F3,
        F4 = __windows.win32.VK_F4,
        F5 = __windows.win32.VK_F5,
        F6 = __windows.win32.VK_F6,
        F7 = __windows.win32.VK_F7,
        F8 = __windows.win32.VK_F8,
        F9 = __windows.win32.VK_F9,
        F10 = __windows.win32.VK_F10,
        F11 = __windows.win32.VK_F11,
        F12 = __windows.win32.VK_F12,
        Dot = __windows.win32.VK_OEM_PERIOD,
        Comma = __windows.win32.VK_OEM_COMMA,
        Plus = __windows.win32.VK_OEM_PLUS,
        Minus = __windows.win32.VK_OEM_MINUS,
        ///\
        BackSlash = __windows.win32.VK_OEM_5,
        Slash = __windows.win32.VK_OEM_2,
        ///[
        LSquareBracket = __windows.win32.VK_OEM_4,
        ///]
        RSquareBracket = __windows.win32.VK_OEM_6,
        ///`
        SwungDash = __windows.win32.VK_OEM_3,
        Insert = __windows.win32.VK_INSERT,
        Home = __windows.win32.VK_HOME,
        PageUp = __windows.win32.VK_PRIOR,
        PageDown = __windows.win32.VK_NEXT,
        Delete = __windows.win32.VK_DELETE,
        End = __windows.win32.VK_END,
        Pause = __windows.win32.VK_PAUSE,
        ///;
        Semicolon = __windows.win32.VK_OEM_1,
        ///'
        Apostrophe = __windows.win32.VK_OEM_7,
        Up = __windows.win32.VK_UP,
        Down = __windows.win32.VK_DOWN,
        Left = __windows.win32.VK_LEFT,
        Right = __windows.win32.VK_RIGHT,
        BackSpace = __windows.win32.VK_BACK,
        Alt = __windows.win32.VK_MENU,
        _,
    }
else if (xfit.platform == .android)
    enum(u16) {
        Unknown = __android.android.AKEYCODE_UNKNOWN,

        SoftLeft = __android.android.AKEYCODE_SOFT_LEFT,
        SoftRight = __android.android.AKEYCODE_SOFT_RIGHT,

        Home = __android.android.AKEYCODE_HOME,
        Back = __android.android.AKEYCODE_BACK,
        Call = __android.android.AKEYCODE_CALL,
        EndCall = __android.android.AKEYCODE_ENDCALL,

        Zero = __android.android.AKEYCODE_0,
        One = __android.android.AKEYCODE_1,
        Two = __android.android.AKEYCODE_2,
        Three = __android.android.AKEYCODE_3,
        Four = __android.android.AKEYCODE_4,
        Five = __android.android.AKEYCODE_5,
        Six = __android.android.AKEYCODE_6,
        Seven = __android.android.AKEYCODE_7,
        Eight = __android.android.AKEYCODE_8,
        Nine = __android.android.AKEYCODE_9,

        Multiply = __android.android.AKEYCODE_STAR,
        Sharp = __android.android.AKEYCODE_POUND,

        Up = __android.android.AKEYCODE_DPAD_UP,
        Down = __android.android.AKEYCODE_DPAD_DOWN,
        Left = __android.android.AKEYCODE_DPAD_LEFT,
        Right = __android.android.AKEYCODE_DPAD_RIGHT,
        Center = __android.android.AKEYCODE_DPAD_CENTER,
        UpLeft = __android.android.AKEYCODE_DPAD_UP_LEFT,
        DownLeft = __android.android.AKEYCODE_DPAD_DOWN_LEFT,
        UpRight = __android.android.AKEYCODE_DPAD_UP_RIGHT,
        DownRight = __android.android.AKEYCODE_DPAD_DOWN_RIGHT,

        VolumeUp = __android.android.AKEYCODE_VOLUME_UP,
        VoulmeDown = __android.android.AKEYCODE_VOLUME_DOWN,

        Power = __android.android.AKEYCODE_POWER,
        Camera = __android.android.AKEYCODE_CAMERA,
        Clear = __android.android.AKEYCODE_CLEAR,

        A = __android.android.AKEYCODE_A,
        B = __android.android.AKEYCODE_B,
        C = __android.android.AKEYCODE_C,
        D = __android.android.AKEYCODE_D,
        E = __android.android.AKEYCODE_E,
        F = __android.android.AKEYCODE_F,
        G = __android.android.AKEYCODE_G,
        H = __android.android.AKEYCODE_H,
        I = __android.android.AKEYCODE_I,
        J = __android.android.AKEYCODE_J,
        K = __android.android.AKEYCODE_K,
        L = __android.android.AKEYCODE_L,
        M = __android.android.AKEYCODE_M,
        N = __android.android.AKEYCODE_N,
        O = __android.android.AKEYCODE_O,
        P = __android.android.AKEYCODE_P,
        Q = __android.android.AKEYCODE_Q,
        R = __android.android.AKEYCODE_R,
        S = __android.android.AKEYCODE_S,
        T = __android.android.AKEYCODE_T,
        U = __android.android.AKEYCODE_U,
        V = __android.android.AKEYCODE_V,
        W = __android.android.AKEYCODE_W,
        X = __android.android.AKEYCODE_X,
        Y = __android.android.AKEYCODE_Y,
        Z = __android.android.AKEYCODE_Z,

        Comma = __android.android.AKEYCODE_COMMA,
        Dot = __android.android.AKEYCODE_PERIOD,
        LAlt = __android.android.AKEYCODE_ALT_LEFT,
        RAlt = __android.android.AKEYCODE_ALT_RIGHT,
        LShift = __android.android.AKEYCODE_SHIFT_LEFT,
        RShift = __android.android.AKEYCODE_SHIFT_RIGHT,
        Tap = __android.android.AKEYCODE_TAB,
        SpaceBar = __android.android.AKEYCODE_SPACE,
        /// Used to enter alternate symbols.
        Sym = __android.android.AKEYCODE_SYM,
        /// Used to launch a browser application.
        Browser = __android.android.AKEYCODE_EXPLORER,
        Mail = __android.android.AKEYCODE_ENVELOPE,
        Enter = __android.android.AKEYCODE_ENTER,
        BackSpace = __android.android.AKEYCODE_DEL,
        ///`
        SwungDash = __android.android.AKEYCODE_GRAVE,
        Minus = __android.android.AKEYCODE_MINUS,
        Equal = __android.android.AKEYCODE_EQUALS,
        ///[
        LSquareBracket = __android.android.AKEYCODE_LEFT_BRACKET,
        ///]
        RSquareBracket = __android.android.AKEYCODE_RIGHT_BRACKET,
        ///\
        BackSlash = __android.android.AKEYCODE_BACKSLASH,
        ///;
        Semicolon = __android.android.AKEYCODE_SEMICOLON,
        ///'
        Apostrophe = __android.android.AKEYCODE_APOSTROPHE,
        /// /
        Slash = __android.android.AKEYCODE_SLASH,
        ///@
        At = __android.android.AKEYCODE_AT,
        Num = __android.android.AKEYCODE_NUM,
        HeadsetHook = __android.android.AKEYCODE_HEADSETHOOK,
        Focus = __android.android.AKEYCODE_FOCUS,
        Plus = __android.android.AKEYCODE_PLUS,
        Menu = __android.android.AKEYCODE_MENU,
        Notification = __android.android.AKEYCODE_NOTIFICATION,
        Search = __android.android.AKEYCODE_SEARCH,

        Play = __android.android.AKEYCODE_MEDIA_PLAY,
        Pause = __android.android.AKEYCODE_MEDIA_PAUSE,
        PlayPause = __android.android.AKEYCODE_MEDIA_PLAY_PAUSE,
        Stop = __android.android.AKEYCODE_MEDIA_STOP,
        Next = __android.android.AKEYCODE_MEDIA_NEXT,
        Prev = __android.android.AKEYCODE_MEDIA_PREVIOUS,
        Rewind = __android.android.AKEYCODE_MEDIA_REWIND,
        FastForward = __android.android.AKEYCODE_MEDIA_FAST_FORWARD,
        MediaClose = __android.android.AKEYCODE_MEDIA_CLOSE,
        MediaEject = __android.android.AKEYCODE_MEDIA_EJECT,
        Record = __android.android.AKEYCODE_MEDIA_RECORD,
        AudioTrack = __android.android.AKEYCODE_MEDIA_AUDIO_TRACK,
        MediaTopMenu = __android.android.AKEYCODE_MEDIA_TOP_MENU,
        SkipForward = __android.android.AKEYCODE_MEDIA_SKIP_FORWARD,
        SkipBackward = __android.android.AKEYCODE_MEDIA_SKIP_BACKWARD,
        StepForward = __android.android.AKEYCODE_MEDIA_STEP_FORWARD,
        StepBackward = __android.android.AKEYCODE_MEDIA_STEP_BACKWARD,

        Mute = __android.android.AKEYCODE_MUTE,
        PageUp = __android.android.AKEYCODE_PAGE_UP,
        PageDown = __android.android.AKEYCODE_PAGE_DOWN,
        PictureSymbols = __android.android.AKEYCODE_PICTSYMBOLS,
        SwitchCharset = __android.android.AKEYCODE_SWITCH_CHARSET,

        ButtonA = __android.android.AKEYCODE_BUTTON_A,
        ButtonB = __android.android.AKEYCODE_BUTTON_B,
        ButtonC = __android.android.AKEYCODE_BUTTON_C,
        ButtonX = __android.android.AKEYCODE_BUTTON_X,
        ButtonY = __android.android.AKEYCODE_BUTTON_Y,
        ButtonZ = __android.android.AKEYCODE_BUTTON_Z,
        ButtonL1 = __android.android.AKEYCODE_BUTTON_L1,
        ButtonR1 = __android.android.AKEYCODE_BUTTON_R1,
        ButtonL2 = __android.android.AKEYCODE_BUTTON_L2,
        ButtonR2 = __android.android.AKEYCODE_BUTTON_R2,
        ButtonLT = __android.android.AKEYCODE_BUTTON_THUMBL,
        ButtonRT = __android.android.AKEYCODE_BUTTON_THUMBR,
        ButtonStart = __android.android.AKEYCODE_BUTTON_START,
        ButtonSelect = __android.android.AKEYCODE_BUTTON_SELECT,
        ButtonMode = __android.android.AKEYCODE_BUTTON_MODE,

        Esc = __android.android.AKEYCODE_ESCAPE,
        ForwardDel = __android.android.AKEYCODE_FORWARD_DEL,
        LCtrl = __android.android.AKEYCODE_CTRL_LEFT,
        RCtrl = __android.android.AKEYCODE_CTRL_RIGHT,
        CapsLock = __android.android.AKEYCODE_CAPS_LOCK,
        ScrollLock = __android.android.AKEYCODE_SCROLL_LOCK,
        MetaLeft = __android.android.AKEYCODE_META_LEFT,
        MetaRight = __android.android.AKEYCODE_META_RIGHT,
        Func = __android.android.AKEYCODE_FUNCTION,
        SysReq = __android.android.AKEYCODE_SYSRQ,
        Break = __android.android.AKEYCODE_BREAK,
        MoveHome = __android.android.AKEYCODE_MOVE_HOME,
        MoveEnd = __android.android.AKEYCODE_MOVE_END,
        Insert = __android.android.AKEYCODE_INSERT,
        Foward = __android.android.AKEYCODE_FORWARD,
        F1 = __android.android.AKEYCODE_F1,
        F2 = __android.android.AKEYCODE_F2,
        F3 = __android.android.AKEYCODE_F3,
        F4 = __android.android.AKEYCODE_F4,
        F5 = __android.android.AKEYCODE_F5,
        F6 = __android.android.AKEYCODE_F6,
        F7 = __android.android.AKEYCODE_F7,
        F8 = __android.android.AKEYCODE_F8,
        F9 = __android.android.AKEYCODE_F9,
        F10 = __android.android.AKEYCODE_F10,
        F11 = __android.android.AKEYCODE_F11,
        F12 = __android.android.AKEYCODE_F12,
        NumLock = __android.android.AKEYCODE_NUM_LOCK,
        Numpad0 = __android.android.AKEYCODE_NUMPAD_0,
        Numpad1 = __android.android.AKEYCODE_NUMPAD_1,
        Numpad2 = __android.android.AKEYCODE_NUMPAD_2,
        Numpad3 = __android.android.AKEYCODE_NUMPAD_3,
        Numpad4 = __android.android.AKEYCODE_NUMPAD_4,
        Numpad5 = __android.android.AKEYCODE_NUMPAD_5,
        Numpad6 = __android.android.AKEYCODE_NUMPAD_6,
        Numpad7 = __android.android.AKEYCODE_NUMPAD_7,
        Numpad8 = __android.android.AKEYCODE_NUMPAD_8,
        Numpad9 = __android.android.AKEYCODE_NUMPAD_9,
        NumpadDivide = __android.android.AKEYCODE_NUMPAD_DIVIDE,
        NumpadMultiply = __android.android.AKEYCODE_NUMPAD_MULTIPLY,
        NumpadSubtract = __android.android.AKEYCODE_NUMPAD_SUBTRACT,
        NumpadAdd = __android.android.AKEYCODE_NUMPAD_ADD,
        NumpadDot = __android.android.AKEYCODE_NUMPAD_DOT,
        NumpadComma = __android.android.AKEYCODE_NUMPAD_COMMA,
        NumpadEnter = __android.android.AKEYCODE_NUMPAD_ENTER,
        NumpadEqual = __android.android.AKEYCODE_NUMPAD_EQUALS,
        NumpadLParen = __android.android.AKEYCODE_NUMPAD_LEFT_PAREN,
        NumpadRParen = __android.android.AKEYCODE_NUMPAD_RIGHT_PAREN,
        VolumeMute = __android.android.AKEYCODE_VOLUME_MUTE,
        ChannelUp = __android.android.AKEYCODE_CHANNEL_UP,
        ChannelDown = __android.android.AKEYCODE_CHANNEL_DOWN,
        ZoomIn = __android.android.AKEYCODE_ZOOM_IN,
        ZoomOut = __android.android.AKEYCODE_ZOOM_OUT,
        TV = __android.android.AKEYCODE_TV,
        Window = __android.android.AKEYCODE_WINDOW,
        Guide = __android.android.AKEYCODE_GUIDE,
        DVR = __android.android.AKEYCODE_DVR,
        Bookmark = __android.android.AKEYCODE_BOOKMARK,
        Captions = __android.android.AKEYCODE_CAPTIONS,
        Settings = __android.android.AKEYCODE_SETTINGS,

        SetTopBoxPower = __android.android.AKEYCODE_STB_POWER,
        SetTopBoxInput = __android.android.AKEYCODE_STB_INPUT,
        AVRPower = __android.android.AKEYCODE_AVR_POWER,
        AVRInput = __android.android.AKEYCODE_AVR_INPUT,

        AppSwitch = __android.android.AKEYCODE_APP_SWITCH,
        Button1 = __android.android.AKEYCODE_BUTTON_1,
        Button2 = __android.android.AKEYCODE_BUTTON_2,
        Button3 = __android.android.AKEYCODE_BUTTON_3,
        Button4 = __android.android.AKEYCODE_BUTTON_4,
        Button5 = __android.android.AKEYCODE_BUTTON_5,
        Button6 = __android.android.AKEYCODE_BUTTON_6,
        Button7 = __android.android.AKEYCODE_BUTTON_7,
        Button8 = __android.android.AKEYCODE_BUTTON_8,
        Button9 = __android.android.AKEYCODE_BUTTON_9,
        Button10 = __android.android.AKEYCODE_BUTTON_10,
        Button11 = __android.android.AKEYCODE_BUTTON_11,
        Button12 = __android.android.AKEYCODE_BUTTON_12,
        Button13 = __android.android.AKEYCODE_BUTTON_13,
        Button14 = __android.android.AKEYCODE_BUTTON_14,
        Button15 = __android.android.AKEYCODE_BUTTON_15,
        Button16 = __android.android.AKEYCODE_BUTTON_16,
        LanguageSwitch = __android.android.AKEYCODE_LANGUAGE_SWITCH,
        MannerMode = __android.android.AKEYCODE_MANNER_MODE,
        Mode3D = __android.android.AKEYCODE_3D_MODE,
        Contacts = __android.android.AKEYCODE_CONTACTS,
        Calendar = __android.android.AKEYCODE_CALENDAR,
        Music = __android.android.AKEYCODE_MUSIC,
        Calc = __android.android.AKEYCODE_CALCULATOR,

        JapaneseZenkakuHankaku = __android.android.AKEYCODE_ZENKAKU_HANKAKU,
        JapaneseEisu = __android.android.AKEYCODE_EISU,
        JapaneseMuhenkan = __android.android.AKEYCODE_MUHENKAN,
        JapaneseHenkan = __android.android.AKEYCODE_HENKAN,
        JapaneseKatakanaHiragana = __android.android.AKEYCODE_KATAKANA_HIRAGANA,
        JapaneseYen = __android.android.AKEYCODE_YEN,
        JapaneseRo = __android.android.AKEYCODE_RO,
        JapaneseKana = __android.android.AKEYCODE_KANA,

        Assist = __android.android.AKEYCODE_ASSIST,
        VoiceAssist = __android.android.AKEYCODE_VOICE_ASSIST,

        BrightnessDown = __android.android.AKEYCODE_BRIGHTNESS_DOWN,
        BrightnessUp = __android.android.AKEYCODE_BRIGHTNESS_UP,
        Sleep = __android.android.AKEYCODE_SLEEP,
        WakeUp = __android.android.AKEYCODE_WAKEUP,
        Pairing = __android.android.AKEYCODE_PAIRING,

        Eleven = __android.android.AKEYCODE_11,
        Twelve = __android.android.AKEYCODE_12,

        LastChannel = __android.android.AKEYCODE_LAST_CHANNEL,

        TVPower = __android.android.AKEYCODE_TV_POWER,
        TVInput = __android.android.AKEYCODE_TV_INPUT,
        TVRed = __android.android.AKEYCODE_PROG_RED,
        TVGreen = __android.android.AKEYCODE_PROG_GREEN,
        TVYellow = __android.android.AKEYCODE_PROG_YELLOW,
        TVBlue = __android.android.AKEYCODE_PROG_BLUE,
        TVDataService = __android.android.AKEYCODE_TV_DATA_SERVICE,
        ToggleTVRadioService = __android.android.AKEYCODE_TV_RADIO_SERVICE,
        TVTeletext = __android.android.AKEYCODE_TV_TELETEXT,
        TVNumberEntry = __android.android.AKEYCODE_TV_NUMBER_ENTRY,
        TVAnologTerrestrial = __android.android.AKEYCODE_TV_TERRESTRIAL_ANALOG,
        TVDigitalTerrestrial = __android.android.AKEYCODE_TV_TERRESTRIAL_DIGITAL,
        TVSatellite = __android.android.AKEYCODE_TV_SATELLITE,
        TVSatelliteBS = __android.android.AKEYCODE_TV_SATELLITE_BS,
        TVSatelliteCS = __android.android.AKEYCODE_TV_SATELLITE_CS,
        TVToggleSatelliteBSOrCS = __android.android.AKEYCODE_TV_SATELLITE_SERVICE,
        TVNetwork = __android.android.AKEYCODE_TV_NETWORK,
        TVToggleAntennaOrCable = __android.android.AKEYCODE_TV_ANTENNA_CABLE,
        TVHDMI1 = __android.android.AKEYCODE_TV_INPUT_HDMI_1,
        TVHDMI2 = __android.android.AKEYCODE_TV_INPUT_HDMI_2,
        TVHDMI3 = __android.android.AKEYCODE_TV_INPUT_HDMI_3,
        TVHDMI4 = __android.android.AKEYCODE_TV_INPUT_HDMI_4,
        TVComposite1 = __android.android.AKEYCODE_TV_INPUT_COMPOSITE_1,
        TVComposite2 = __android.android.AKEYCODE_TV_INPUT_COMPOSITE_2,
        TVComponent1 = __android.android.AKEYCODE_TV_INPUT_COMPONENT_1,
        TVComponent2 = __android.android.AKEYCODE_TV_INPUT_COMPONENT_2,
        TVVGA = __android.android.AKEYCODE_TV_INPUT_VGA_1,
        TVToggleAudioDescription = __android.android.AKEYCODE_TV_AUDIO_DESCRIPTION,
        TVAudioDescriptionMixUp = __android.android.AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_UP,
        TVAudioDescriptionMixDown = __android.android.AKEYCODE_TV_AUDIO_DESCRIPTION_MIX_DOWN,
        TVZoomMode = __android.android.AKEYCODE_TV_ZOOM_MODE,
        TVContentsMenu = __android.android.AKEYCODE_TV_CONTENTS_MENU,
        TVMediaContextMenu = __android.android.AKEYCODE_TV_MEDIA_CONTEXT_MENU,
        TVTimerProgramming = __android.android.AKEYCODE_TV_TIMER_PROGRAMMING,

        Help = __android.android.AKEYCODE_HELP,

        NavigatePrev = __android.android.AKEYCODE_NAVIGATE_PREVIOUS,
        NavigateNext = __android.android.AKEYCODE_NAVIGATE_NEXT,
        NavigateIn = __android.android.AKEYCODE_NAVIGATE_IN,
        NavigateOut = __android.android.AKEYCODE_NAVIGATE_OUT,

        StemPrimary = __android.android.AKEYCODE_STEM_PRIMARY,
        Stem1 = __android.android.AKEYCODE_STEM_1,
        Stem2 = __android.android.AKEYCODE_STEM_2,
        Stem3 = __android.android.AKEYCODE_STEM_3,

        SoftSleep = __android.android.AKEYCODE_SOFT_SLEEP,

        Cut = __android.android.AKEYCODE_CUT,
        Copy = __android.android.AKEYCODE_COPY,
        Paste = __android.android.AKEYCODE_PASTE,

        FingerprintNavigationUp = __android.android.AKEYCODE_SYSTEM_NAVIGATION_UP,
        FingerprintNavigationDown = __android.android.AKEYCODE_SYSTEM_NAVIGATION_DOWN,
        FingerprintNavigationLeft = __android.android.AKEYCODE_SYSTEM_NAVIGATION_LEFT,
        FingerprintNavigationRight = __android.android.AKEYCODE_SYSTEM_NAVIGATION_RIGHT,

        AllApps = __android.android.AKEYCODE_ALL_APPS,
        Refresh = __android.android.AKEYCODE_REFRESH,

        ThumbsUp = __android.android.AKEYCODE_THUMBS_UP,
        ThumbsDown = __android.android.AKEYCODE_THUMBS_DOWN,

        ProfileSwitch = __android.android.AKEYCODE_PROFILE_SWITCH,
        _,
    }
else if (xfit.platform == .linux) enum(u16) {
    Reserved = __linux.c.KEY_RESERVED,
    Esc = __linux.c.KEY_ESC,
    One = __linux.c.KEY_1,
    Two = __linux.c.KEY_2,
    Three = __linux.c.KEY_3,
    Four = __linux.c.KEY_4,
    Five = __linux.c.KEY_5,
    Six = __linux.c.KEY_6,
    Seven = __linux.c.KEY_7,
    Eight = __linux.c.KEY_8,
    Nine = __linux.c.KEY_9,
    Zero = __linux.c.KEY_0,
    Minus = __linux.c.KEY_MINUS,
    Equal = __linux.c.KEY_EQUAL,
    BackSpace = __linux.c.KEY_BACKSPACE,
    Tap = __linux.c.KEY_TAB,
    Q = __linux.c.KEY_Q,
    W = __linux.c.KEY_W,
    E = __linux.c.KEY_E,
    R = __linux.c.KEY_R,
    T = __linux.c.KEY_T,
    Y = __linux.c.KEY_Y,
    U = __linux.c.KEY_U,
    I = __linux.c.KEY_I,
    O = __linux.c.KEY_O,
    P = __linux.c.KEY_P,
    LBrace = __linux.c.KEY_LEFTBRACE,
    RBrace = __linux.c.KEY_RIGHTBRACE,
    Enter = __linux.c.KEY_ENTER,
    LCtrl = __linux.c.KEY_LEFTCTRL,
    A = __linux.c.KEY_A,
    S = __linux.c.KEY_S,
    D = __linux.c.KEY_D,
    F = __linux.c.KEY_F,
    G = __linux.c.KEY_G,
    H = __linux.c.KEY_H,
    J = __linux.c.KEY_J,
    K = __linux.c.KEY_K,
    L = __linux.c.KEY_L,
    Senucolon = __linux.c.KEY_SEMICOLON,
    Apostrophe = __linux.c.KEY_APOSTROPHE,
    Grave = __linux.c.KEY_GRAVE,
    LeftShift = __linux.c.KEY_LEFTSHIFT,
    BackSlash = __linux.c.KEY_BACKSLASH,
    Z = __linux.c.KEY_Z,
    X = __linux.c.KEY_X,
    C = __linux.c.KEY_C,
    V = __linux.c.KEY_V,
    B = __linux.c.KEY_B,
    N = __linux.c.KEY_N,
    M = __linux.c.KEY_M,
    Comma = __linux.c.KEY_COMMA,
    Dot = __linux.c.KEY_DOT,
    Slash = __linux.c.KEY_SLASH,
    RShift = __linux.c.KEY_RIGHTSHIFT,
    NumpadMultiply = __linux.c.KEY_KPASTERISK,
    LAlt = __linux.c.KEY_LEFTALT,
    Space = __linux.c.KEY_SPACE,
    CapsLock = __linux.c.KEY_CAPSLOCK,
    F1 = __linux.c.KEY_F1,
    F2 = __linux.c.KEY_F2,
    F3 = __linux.c.KEY_F3,
    F4 = __linux.c.KEY_F4,
    F5 = __linux.c.KEY_F5,
    F6 = __linux.c.KEY_F6,
    F7 = __linux.c.KEY_F7,
    F8 = __linux.c.KEY_F8,
    F9 = __linux.c.KEY_F9,
    F10 = __linux.c.KEY_F10,
    NumLock = __linux.c.KEY_NUMLOCK,
    ScrollLock = __linux.c.KEY_SCROLLLOCK,
    Numpad7 = __linux.c.KEY_KP7,
    Numpad8 = __linux.c.KEY_KP8,
    Numpad9 = __linux.c.KEY_KP9,
    NumpadMinus = __linux.c.KEY_KPMINUS,
    Numpad4 = __linux.c.KEY_KP4,
    Numpad5 = __linux.c.KEY_KP5,
    Numpad6 = __linux.c.KEY_KP6,
    NumpadPlus = __linux.c.KEY_KPPLUS,
    Numpad1 = __linux.c.KEY_KP1,
    Numpad2 = __linux.c.KEY_KP2,
    Numpad3 = __linux.c.KEY_KP3,
    Numpad0 = __linux.c.KEY_KP0,
    NumpadDot = __linux.c.KEY_KPDOT,

    ZenkakuHankaku = __linux.c.KEY_ZENKAKUHANKAKU,
    @"102nd" = __linux.c.KEY_102ND,
    F11 = __linux.c.KEY_F11,
    F12 = __linux.c.KEY_F12,
    R0 = __linux.c.KEY_RO,
    Katakana = __linux.c.KEY_KATAKANA,
    Hiragana = __linux.c.KEY_HIRAGANA,
    Henkan = __linux.c.KEY_HENKAN,
    KatakanaHiragana = __linux.c.KEY_KATAKANAHIRAGANA,
    Muhekan = __linux.c.KEY_MUHENKAN,
    NumpadJPComma = __linux.c.KEY_KPJPCOMMA,
    NumpadEnter = __linux.c.KEY_KPENTER,
    RCtrl = __linux.c.KEY_RIGHTCTRL,
    NumpadDivide = __linux.c.KEY_KPSLASH,
    SysRQ = __linux.c.KEY_SYSRQ,
    RAlt = __linux.c.KEY_RIGHTALT,
    LineFeed = __linux.c.KEY_LINEFEED,
    Home = __linux.c.KEY_HOME,
    Up = __linux.c.KEY_UP,
    PageUp = __linux.c.KEY_PAGEUP,
    Left = __linux.c.KEY_LEFT,
    Right = __linux.c.KEY_RIGHT,
    End = __linux.c.KEY_END,
    Down = __linux.c.KEY_DOWN,
    PageDown = __linux.c.KEY_PAGEDOWN,
    Insert = __linux.c.KEY_INSERT,
    Delete = __linux.c.KEY_DELETE,
    Macro = __linux.c.KEY_MACRO,
    Mute = __linux.c.KEY_MUTE,
    VolumeDown = __linux.c.KEY_VOLUMEDOWN,
    VolumeUp = __linux.c.KEY_VOLUMEUP,
    Power = __linux.c.KEY_POWER,
    NumpadEqual = __linux.c.KEY_KPEQUAL,
    NumpadPlusMinus = __linux.c.KEY_KPPLUSMINUS,
    Pause = __linux.c.KEY_PAUSE,
    Scale = __linux.c.KEY_SCALE,

    NumpadComma = __linux.c.KEY_KPCOMMA,
    Hanguel = __linux.c.KEY_HANGUEL,
    Hanja = __linux.c.KEY_HANJA,
    Yen = __linux.c.KEY_YEN,
    LeftMeta = __linux.c.KEY_LEFTMETA,
    RightMeta = __linux.c.KEY_RIGHTMETA,
    Compose = __linux.c.KEY_COMPOSE,

    Stop = __linux.c.KEY_STOP,
    Again = __linux.c.KEY_AGAIN,
    Props = __linux.c.KEY_PROPS,
    Undo = __linux.c.KEY_UNDO,
    Front = __linux.c.KEY_FRONT,
    Copy = __linux.c.KEY_COPY,
    Open = __linux.c.KEY_OPEN,
    Paste = __linux.c.KEY_PASTE,
    Find = __linux.c.KEY_FIND,
    Cut = __linux.c.KEY_CUT,
    Help = __linux.c.KEY_HELP,
    Menu = __linux.c.KEY_MENU,
    Calc = __linux.c.KEY_CALC,
    Setup = __linux.c.KEY_SETUP,
    Sleep = __linux.c.KEY_SLEEP,
    WakeUp = __linux.c.KEY_WAKEUP,
    File = __linux.c.KEY_FILE,
    SendFile = __linux.c.KEY_SENDFILE,
    DeleteFile = __linux.c.KEY_DELETEFILE,
    XFer = __linux.c.KEY_XFER,
    Prog1 = __linux.c.KEY_PROG1,
    Prog2 = __linux.c.KEY_PROG2,
    WWW = __linux.c.KEY_WWW,
    MSDos = __linux.c.KEY_MSDOS,
    Coffee = __linux.c.KEY_COFFEE,
    RotateDisplay = __linux.c.KEY_ROTATE_DISPLAY,
    Mail = __linux.c.KEY_MAIL,
    BookMarks = __linux.c.KEY_BOOKMARKS,
    Computer = __linux.c.KEY_COMPUTER,
    Back = __linux.c.KEY_BACK,
    Forward = __linux.c.KEY_FORWARD,
    CloseCD = __linux.c.KEY_CLOSECD,
    EjectCD = __linux.c.KEY_EJECTCD,
    EjectCloseCD = __linux.c.KEY_EJECTCLOSECD,
    NextSong = __linux.c.KEY_NEXTSONG,
    PlayPause = __linux.c.KEY_PLAYPAUSE,
    PrevSong = __linux.c.KEY_PREVIOUSSONG,
    StopCD = __linux.c.KEY_STOPCD,
    Record = __linux.c.KEY_RECORD,
    Rewind = __linux.c.KEY_REWIND,
    Phone = __linux.c.KEY_PHONE,
    ISO = __linux.c.KEY_ISO,
    Config = __linux.c.KEY_CONFIG,
    HomePage = __linux.c.KEY_HOMEPAGE,
    Refresh = __linux.c.KEY_REFRESH,
    Exit = __linux.c.KEY_EXIT,
    Move = __linux.c.KEY_MOVE,
    Edit = __linux.c.KEY_EDIT,
    ScrollUp = __linux.c.KEY_SCROLLUP,
    ScrollDown = __linux.c.KEY_SCROLLDOWN,
    KpLeftParen = __linux.c.KEY_KPLEFTPAREN,
    KpRightParen = __linux.c.KEY_KPRIGHTPAREN,
    New = __linux.c.KEY_NEW,
    Redo = __linux.c.KEY_REDO,

    F13 = __linux.c.KEY_F13,
    F14 = __linux.c.KEY_F14,
    F15 = __linux.c.KEY_F15,
    F16 = __linux.c.KEY_F16,
    F17 = __linux.c.KEY_F17,
    F18 = __linux.c.KEY_F18,
    F19 = __linux.c.KEY_F19,
    F20 = __linux.c.KEY_F20,
    F21 = __linux.c.KEY_F21,
    F22 = __linux.c.KEY_F22,
    F23 = __linux.c.KEY_F23,
    F24 = __linux.c.KEY_F24,

    Playcd = __linux.c.KEY_PLAYCD,
    Pausecd = __linux.c.KEY_PAUSECD,
    Prog3 = __linux.c.KEY_PROG3,
    Prog4 = __linux.c.KEY_PROG4,
    Dashboard = __linux.c.KEY_DASHBOARD,
    Suspend = __linux.c.KEY_SUSPEND,
    Close = __linux.c.KEY_CLOSE,
    Play = __linux.c.KEY_PLAY,
    FastForward = __linux.c.KEY_FASTFORWARD,
    BaseBoost = __linux.c.KEY_BASSBOOST,
    Print = __linux.c.KEY_PRINT,
    Hp = __linux.c.KEY_HP,
    Camera = __linux.c.KEY_CAMERA,
    Sound = __linux.c.KEY_SOUND,
    Question = __linux.c.KEY_QUESTION,
    Email = __linux.c.KEY_EMAIL,
    Chat = __linux.c.KEY_CHAT,
    Search = __linux.c.KEY_SEARCH,
    Connect = __linux.c.KEY_CONNECT,
    Finance = __linux.c.KEY_FINANCE,
    Sport = __linux.c.KEY_SPORT,
    Alterase = __linux.c.KEY_ALTERASE,
    Cancel = __linux.c.KEY_CANCEL,
    BrightnessDown = __linux.c.KEY_BRIGHTNESSDOWN,
    BrightnessUp = __linux.c.KEY_BRIGHTNESSUP,
    Media = __linux.c.KEY_MEDIA,

    SwitchVideoMode = __linux.c.KEY_SWITCHVIDEOMODE,

    KbdillumMiddle = __linux.c.KEY_KBDILLUMTOGGLE,
    KbdillumDown = __linux.c.KEY_KBDILLUMDOWN,
    KbdillumUp = __linux.c.KEY_KBDILLUMUP,

    Send = __linux.c.KEY_SEND,
    Reply = __linux.c.KEY_REPLY,
    ForwardMail = __linux.c.KEY_FORWARDMAIL,
    Save = __linux.c.KEY_SAVE,
    Documents = __linux.c.KEY_DOCUMENTS,

    Battery = __linux.c.KEY_BATTERY,

    BlueTooth = __linux.c.KEY_BLUETOOTH,
    WLAN = __linux.c.KEY_WLAN,
    UWB = __linux.c.KEY_UWB,

    Unknown = __linux.c.KEY_UNKNOWN,

    VideoNext = __linux.c.KEY_VIDEO_NEXT,
    VideoPrev = __linux.c.KEY_VIDEO_PREV,
    BrightnessCycle = __linux.c.KEY_BRIGHTNESS_CYCLE,
    BrightnessAuto = __linux.c.KEY_BRIGHTNESS_AUTO,
    DisplayOff = __linux.c.KEY_DISPLAY_OFF,

    WWan = __linux.c.KEY_WWAN,
    RFKill = __linux.c.KEY_RFKILL,

    MicMute = __linux.c.KEY_MICMUTE,

    OK = __linux.c.KEY_OK,
    Select = __linux.c.KEY_SELECT,
    Goto = __linux.c.KEY_GOTO,
    Clear = __linux.c.KEY_CLEAR,
    Power2 = __linux.c.KEY_POWER2,
    Option = __linux.c.KEY_OPTION,
    Info = __linux.c.KEY_INFO,
    Time = __linux.c.KEY_TIME,
    Vendor = __linux.c.KEY_VENDOR,
    Archive = __linux.c.KEY_ARCHIVE,
    Program = __linux.c.KEY_PROGRAM,
    Channel = __linux.c.KEY_CHANNEL,
    Favorite = __linux.c.KEY_FAVORITES,
    Epg = __linux.c.KEY_EPG,
    PVR = __linux.c.KEY_PVR,
    MHP = __linux.c.KEY_MHP,
    Language = __linux.c.KEY_LANGUAGE,
    Title = __linux.c.KEY_TITLE,
    SubTitle = __linux.c.KEY_SUBTITLE,
    Angle = __linux.c.KEY_ANGLE,
    FullScreen = __linux.c.KEY_FULL_SCREEN,
    Mode = __linux.c.KEY_MODE,
    KeyBoard = __linux.c.KEY_KEYBOARD,
    AspectRatio = __linux.c.KEY_ASPECT_RATIO,
    PC = __linux.c.KEY_PC,
    TV = __linux.c.KEY_TV,
    TV2 = __linux.c.KEY_TV2,
    VCR = __linux.c.KEY_VCR,
    VCR2 = __linux.c.KEY_VCR2,
    SAT = __linux.c.KEY_SAT,
    SAT2 = __linux.c.KEY_SAT2,
    CD = __linux.c.KEY_CD,
    TAPE = __linux.c.KEY_TAPE,
    RADIO = __linux.c.KEY_RADIO,
    Tuner = __linux.c.KEY_TUNER,
    Player = __linux.c.KEY_PLAYER,
    Text = __linux.c.KEY_TEXT,
    DVD = __linux.c.KEY_DVD,
    AUX = __linux.c.KEY_AUX,
    MP3 = __linux.c.KEY_MP3,
    Audio = __linux.c.KEY_AUDIO,
    Video = __linux.c.KEY_VIDEO,
    Directory = __linux.c.KEY_DIRECTORY,
    List = __linux.c.KEY_LIST,
    Memo = __linux.c.KEY_MEMO,
    Calendar = __linux.c.KEY_CALENDAR,
    Red = __linux.c.KEY_RED,
    Green = __linux.c.KEY_GREEN,
    Yellow = __linux.c.KEY_YELLOW,
    Blue = __linux.c.KEY_BLUE,
    ChannelUp = __linux.c.KEY_CHANNELUP,
    ChannelDown = __linux.c.KEY_CHANNELDOWN,
    First = __linux.c.KEY_FIRST,
    Last = __linux.c.KEY_LAST,
    AB = __linux.c.KEY_AB,
    Next = __linux.c.KEY_NEXT,
    Restart = __linux.c.KEY_RESTART,
    Slow = __linux.c.KEY_SLOW,
    Shuffle = __linux.c.KEY_SHUFFLE,
    Break = __linux.c.KEY_BREAK,
    Prev = __linux.c.KEY_PREVIOUS,
    Digits = __linux.c.KEY_DIGITS,
    Teen = __linux.c.KEY_TEEN,
    Twen = __linux.c.KEY_TWEN,
    VideoPhone = __linux.c.KEY_VIDEOPHONE,
    Games = __linux.c.KEY_GAMES,
    ZoomIn = __linux.c.KEY_ZOOMIN,
    ZoomOut = __linux.c.KEY_ZOOMOUT,
    ZoomReset = __linux.c.KEY_ZOOMRESET,
    WordProcessor = __linux.c.KEY_WORDPROCESSOR,
    Editor = __linux.c.KEY_EDITOR,
    SpreadSheet = __linux.c.KEY_SPREADSHEET,
    GraphicsEditor = __linux.c.KEY_GRAPHICSEDITOR,
    Presentation = __linux.c.KEY_PRESENTATION,
    DataBase = __linux.c.KEY_DATABASE,
    News = __linux.c.KEY_NEWS,
    VoiceMail = __linux.c.KEY_VOICEMAIL,
    AddressBook = __linux.c.KEY_ADDRESSBOOK,
    Messenger = __linux.c.KEY_MESSENGER,
    DisplayToggle = __linux.c.KEY_DISPLAYTOGGLE,
    SpellCheck = __linux.c.KEY_SPELLCHECK,
    LogOff = __linux.c.KEY_LOGOFF,

    Dollar = __linux.c.KEY_DOLLAR,
    Euro = __linux.c.KEY_EURO,

    FrameBack = __linux.c.KEY_FRAMEBACK,
    FrameForward = __linux.c.KEY_FRAMEFORWARD,
    ContextMenu = __linux.c.KEY_CONTEXT_MENU,
    MediaRepeat = __linux.c.KEY_MEDIA_REPEAT,
    @"10ChannelsUp" = __linux.c.KEY_10CHANNELSUP,
    @"10ChannelsDown" = __linux.c.KEY_10CHANNELSDOWN,
    Image = __linux.c.KEY_IMAGES,
    NotificationCenter = __linux.c.KEY_NOTIFICATION_CENTER,
    PickupPhone = __linux.c.KEY_PICKUP_PHONE,
    HangupPhone = __linux.c.KEY_HANGUP_PHONE,

    DelEOL = __linux.c.KEY_DEL_EOL,
    DelEOS = __linux.c.KEY_DEL_EOS,
    InsLine = __linux.c.KEY_INS_LINE,
    DelLine = __linux.c.KEY_DEL_LINE,

    Fn = __linux.c.KEY_FN,
    FnEsc = __linux.c.KEY_FN_ESC,
    FnF1 = __linux.c.KEY_FN_F1,
    FnF2 = __linux.c.KEY_FN_F2,
    FnF3 = __linux.c.KEY_FN_F3,
    FnF4 = __linux.c.KEY_FN_F4,
    FnF5 = __linux.c.KEY_FN_F5,
    FnF6 = __linux.c.KEY_FN_F6,
    FnF7 = __linux.c.KEY_FN_F7,
    FnF8 = __linux.c.KEY_FN_F8,
    FnF9 = __linux.c.KEY_FN_F9,
    FnF10 = __linux.c.KEY_FN_F10,
    FnF11 = __linux.c.KEY_FN_F11,
    FnF12 = __linux.c.KEY_FN_F12,
    Fn1 = __linux.c.KEY_FN_1,
    Fn2 = __linux.c.KEY_FN_2,
    FnD = __linux.c.KEY_FN_D,
    FnE = __linux.c.KEY_FN_E,
    FnF = __linux.c.KEY_FN_F,
    FnS = __linux.c.KEY_FN_S,
    FnB = __linux.c.KEY_FN_B,
    FnRShift = __linux.c.KEY_FN_RIGHT_SHIFT,

    BrlDot1 = __linux.c.KEY_BRL_DOT1,
    BrlDot2 = __linux.c.KEY_BRL_DOT2,
    BrlDot3 = __linux.c.KEY_BRL_DOT3,
    BrlDot4 = __linux.c.KEY_BRL_DOT4,
    BrlDot5 = __linux.c.KEY_BRL_DOT5,
    BrlDot6 = __linux.c.KEY_BRL_DOT6,
    BrlDot7 = __linux.c.KEY_BRL_DOT7,
    BrlDot8 = __linux.c.KEY_BRL_DOT8,
    BrlDot9 = __linux.c.KEY_BRL_DOT9,
    BrlDot10 = __linux.c.KEY_BRL_DOT10,

    CameraFocus = __linux.c.KEY_CAMERA_FOCUS,
    WPSButton = __linux.c.KEY_WPS_BUTTON,

    TouchPadToggle = __linux.c.KEY_TOUCHPAD_TOGGLE,
    TouchPadOn = __linux.c.KEY_TOUCHPAD_ON,
    TouchPadOff = __linux.c.KEY_TOUCHPAD_OFF,

    CameraZoomIn = __linux.c.KEY_CAMERA_ZOOMIN,
    CameraZoomOut = __linux.c.KEY_CAMERA_ZOOMOUT,
    CameraUp = __linux.c.KEY_CAMERA_UP,
    CameraDown = __linux.c.KEY_CAMERA_DOWN,
    CameraLeft = __linux.c.KEY_CAMERA_LEFT,
    CameraRight = __linux.c.KEY_CAMERA_RIGHT,

    AttendantOn = __linux.c.KEY_ATTENDANT_ON,
    AttendantOff = __linux.c.KEY_ATTENDANT_OFF,
    AttendantToggle = __linux.c.KEY_ATTENDANT_TOGGLE,
    KeyLightToggle = __linux.c.KEY_LIGHTS_TOGGLE,

    AlsToggle = __linux.c.KEY_ALS_TOGGLE,
    RotateLockToggle = __linux.c.KEY_ROTATE_LOCK_TOGGLE,

    ButtonConfig = __linux.c.KEY_BUTTONCONFIG,
    TaskManager = __linux.c.KEY_TASKMANAGER,
    Journal = __linux.c.KEY_JOURNAL,
    ControlPanel = __linux.c.KEY_CONTROLPANEL,
    AppSelect = __linux.c.KEY_APPSELECT,
    ScreenSaver = __linux.c.KEY_SCREENSAVER,
    VoiceCommand = __linux.c.KEY_VOICECOMMAND,
    Assistant = __linux.c.KEY_ASSISTANT,
    KeyboardLayoutNext = __linux.c.KEY_KBD_LAYOUT_NEXT,
    EmojiPicker = __linux.c.KEY_EMOJI_PICKER,

    BrightnessMin = __linux.c.KEY_BRIGHTNESS_MIN,
    BrightnessMax = __linux.c.KEY_BRIGHTNESS_MAX,

    KeyboardInputAssistPrev = __linux.c.KEY_KBDINPUTASSIST_PREV,
    KeyboardInputAssistNext = __linux.c.KEY_KBDINPUTASSIST_NEXT,
    KeyboardInputAssistPrevGroup = __linux.c.KEY_KBDINPUTASSIST_PREVGROUP,
    KeyboardInputAssistNextGroup = __linux.c.KEY_KBDINPUTASSIST_NEXTGROUP,
    KeyboardInputAssistAccept = __linux.c.KEY_KBDINPUTASSIST_ACCEPT,
    KeyboardInputAssistCancel = __linux.c.KEY_KBDINPUTASSIST_CANCEL,

    RightUp = __linux.c.KEY_RIGHT_UP,
    RightDown = __linux.c.KEY_RIGHT_DOWN,
    LeftUp = __linux.c.KEY_LEFT_UP,
    LeftDown = __linux.c.KEY_LEFT_DOWN,

    RootMenu = __linux.c.KEY_ROOT_MENU,
    TopMenu = __linux.c.KEY_MEDIA_TOP_MENU,
    AudioDesc = __linux.c.KEY_AUDIO_DESC,
    @"3DMode" = __linux.c.KEY_3D_MODE,
    NextFavorite = __linux.c.KEY_NEXT_FAVORITE,
    StopRecord = __linux.c.KEY_STOP_RECORD,
    PauseRecord = __linux.c.KEY_PAUSE_RECORD,
    VOD = __linux.c.KEY_VOD,
    Unmute = __linux.c.KEY_UNMUTE,
    FastReverse = __linux.c.KEY_FASTREVERSE,
    SlowReverse = __linux.c.KEY_SLOWREVERSE,
    Data = __linux.c.KEY_DATA,
    OnScreenKeyboard = __linux.c.KEY_ONSCREEN_KEYBOARD,
    PrivacyScreenToggle = __linux.c.KEY_PRIVACY_SCREEN_TOGGLE,

    Macro1 = __linux.c.KEY_MACRO1,
    Macro2 = __linux.c.KEY_MACRO2,
    Macro3 = __linux.c.KEY_MACRO3,
    Macro4 = __linux.c.KEY_MACRO4,
    Macro5 = __linux.c.KEY_MACRO5,
    Macro6 = __linux.c.KEY_MACRO6,
    Macro7 = __linux.c.KEY_MACRO7,
    Macro8 = __linux.c.KEY_MACRO8,
    Macro9 = __linux.c.KEY_MACRO9,
    Macro10 = __linux.c.KEY_MACRO10,
    Macro11 = __linux.c.KEY_MACRO11,
    Macro12 = __linux.c.KEY_MACRO12,
    Macro13 = __linux.c.KEY_MACRO13,
    Macro14 = __linux.c.KEY_MACRO14,
    Macro15 = __linux.c.KEY_MACRO15,
    Macro16 = __linux.c.KEY_MACRO16,
    Macro17 = __linux.c.KEY_MACRO17,
    Macro18 = __linux.c.KEY_MACRO18,
    Macro19 = __linux.c.KEY_MACRO19,
    Macro20 = __linux.c.KEY_MACRO20,
    Macro21 = __linux.c.KEY_MACRO21,
    Macro22 = __linux.c.KEY_MACRO22,
    Macro23 = __linux.c.KEY_MACRO23,
    Macro24 = __linux.c.KEY_MACRO24,
    Macro25 = __linux.c.KEY_MACRO25,
    Macro26 = __linux.c.KEY_MACRO26,
    Macro27 = __linux.c.KEY_MACRO27,
    Macro28 = __linux.c.KEY_MACRO28,
    Macro29 = __linux.c.KEY_MACRO29,
    Macro30 = __linux.c.KEY_MACRO30,

    RecordStart = __linux.c.KEY_MACRO_RECORD_START,
    RecordStop = __linux.c.KEY_MACRO_RECORD_STOP,
    RecordCycle = __linux.c.KEY_MACRO_PRESET_CYCLE,
    Preset1 = __linux.c.KEY_MACRO_PRESET1,
    Preset2 = __linux.c.KEY_MACRO_PRESET2,
    Preset3 = __linux.c.KEY_MACRO_PRESET3,

    KeyboardLCDMenu1 = __linux.c.KEY_KBD_LCD_MENU1,
    KeyboardLCDMenu2 = __linux.c.KEY_KBD_LCD_MENU2,
    KeyboardLCDMenu3 = __linux.c.KEY_KBD_LCD_MENU3,
    KeyboardLCDMenu4 = __linux.c.KEY_KBD_LCD_MENU4,
    KeyboardLCDMenu5 = __linux.c.KEY_KBD_LCD_MENU5,
} else @compileError("not support platform");

pub inline fn set_Lmouse_down_func(_func: *const fn (pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.Lmouse_down_func), &__system.Lmouse_down_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_Rmouse_down_func(_func: *const fn (pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.Rmouse_down_func), &__system.Rmouse_down_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_Mmouse_down_func(_func: *const fn (pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.Mmouse_down_func), &__system.Mmouse_down_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_Lmouse_up_func(_func: *const fn (pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.Lmouse_up_func), &__system.Lmouse_up_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_Rmouse_up_func(_func: *const fn (pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.Rmouse_up_func), &__system.Rmouse_up_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_Mmouse_up_func(_func: *const fn (pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.Mmouse_up_func), &__system.Mmouse_up_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_key_down_func(_func: *const fn (key) void) void {
    @atomicStore(@TypeOf(__system.key_down_func), &__system.key_down_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_key_up_func(_func: *const fn (key) void) void {
    @atomicStore(@TypeOf(__system.key_up_func), &__system.key_up_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_mouse_move_func(_func: *const fn (pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.mouse_move_func), &__system.mouse_move_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_touch_down_func(_func: *const fn (touch_idx: u32, pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.touch_down_func), &__system.touch_down_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_touch_up_func(_func: *const fn (touch_idx: u32, pos: math.point) void) void {
    @atomicStore(@TypeOf(__system.touch_up_func), &__system.touch_up_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_mouse_hover_func(_func: *const fn () void) void {
    @atomicStore(@TypeOf(__system.mouse_hover_func), &__system.mouse_hover_func, _func, std.builtin.AtomicOrder.monotonic);
}
pub inline fn set_mouse_out_func(_func: *const fn () void) void {
    @atomicStore(@TypeOf(__system.mouse_leave_func), &__system.mouse_leave_func, _func, std.builtin.AtomicOrder.monotonic);
}

pub inline fn Lmouse_down() bool {
    return __system.Lmouse_click.load(std.builtin.AtomicOrder.monotonic);
}
pub inline fn Mmouse_down() bool {
    return __system.Mmouse_click.load(std.builtin.AtomicOrder.monotonic);
}
pub inline fn Rmouse_down() bool {
    return __system.Rmouse_click.load(std.builtin.AtomicOrder.monotonic);
}
pub inline fn Lmouse_up() bool {
    return !__system.Lmouse_click.load(std.builtin.AtomicOrder.monotonic);
}
pub inline fn Mmouse_up() bool {
    return !__system.Mmouse_click.load(std.builtin.AtomicOrder.monotonic);
}
pub inline fn Rmouse_up() bool {
    return !__system.Rmouse_click.load(std.builtin.AtomicOrder.monotonic);
}
///false -> up, true -> down
pub inline fn key_down_or_up(_key: key) bool {
    if (@intFromEnum(_key) >= __system.__linux.c.KEY_SIZE) {
        xfit.print("WARN key_down_or_up out of range __system.keys[{d}] value : {d}\n", .{ __system.__linux.c.KEY_SIZE, @intFromEnum(_key) });
        return false;
    }
    return __system.keys[@intFromEnum(_key)].load(std.builtin.AtomicOrder.monotonic);
}
pub inline fn get_cursor_pos() math.point {
    const p: math.point = .{
        @atomicLoad(f32, &__system.cursor_pos[0], std.builtin.AtomicOrder.monotonic),
        @atomicLoad(f32, &__system.cursor_pos[1], std.builtin.AtomicOrder.monotonic),
    };
    return p;
}
pub inline fn get_mouse_scroll_dt() i32 {
    return __system.mouse_scroll_dt.load(std.builtin.AtomicOrder.monotonic);
}
pub fn convert_set_mouse_pos(mouse_pos: math.point) math.point {
    const mx: f32 = mouse_pos[0];
    const my: f32 = mouse_pos[1];
    const w = @as(f32, @floatFromInt(window.window_width())) / 2.0;
    const h = @as(f32, @floatFromInt(window.window_height())) / 2.0;
    const mm = math.point{ mx - w, -my + h };
    @atomicStore(f32, &__system.cursor_pos[0], mm[0], std.builtin.AtomicOrder.monotonic);
    @atomicStore(f32, &__system.cursor_pos[1], mm[1], std.builtin.AtomicOrder.monotonic);
    return mm;
}
pub fn convert_mouse_pos(mouse_pos: math.point) math.point {
    const mx: f32 = mouse_pos[0];
    const my: f32 = mouse_pos[1];
    const w = @as(f32, @floatFromInt(window.window_width())) / 2.0;
    const h = @as(f32, @floatFromInt(window.window_height())) / 2.0;
    const mm = math.point{ mx - w, -my + h };
    return mm;
}
